### ISSUE TITLE
Maybe me...?

### ISSUE THREAD

**Issue by CrypticKingJoe** [vinesmsuic/Bot-Chen#1]
So I ran this in heroku
my bot came up and so on
but when I do say .help or .ping the bot does not respond
any reason for this?

**Comment by CrypticKingJoe** [comment]
019-12-02T06:36:29.395924+00:00 app[worker.1]:     at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)

2019-12-02T06:36:29.395926+00:00 app[worker.1]:     at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)

2019-12-02T06:36:29.395929+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)

2019-12-02T06:36:29.395932+00:00 app[worker.1]:     at WebSocket.emit (events.js:210:5)

2019-12-02T06:36:29.395934+00:00 app[worker.1]:     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:789:20)

2019-12-02T06:36:29.395936+00:00 app[worker.1]:     at Receiver.emit (events.js:210:5)

2019-12-02T06:36:29.395945+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

**Comment by CrypticKingJoe** [comment]
2019-12-02T06:43:54.213245+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: ReferenceError: botconfig is not defined
